# Generated by Django 5.1.4 on 2025-01-06 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('utility_name', models.CharField(max_length=50)),
                ('utility_description', models.TextField()),
                ('type', models.CharField(choices=[('NA', 'Not Applicable'), ('DU', 'Daily Use'), ('MT', 'Mathematical'), ('FH', 'File Handling')], default='NA', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
