# Generated by Django 5.1.4 on 2025-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='utility_status',
            field=models.CharField(choices=[('UD', 'Under Development'), ('AC', 'Active'), ('IA', 'Inactive'), ('DF', 'Deferred')], default='UD', max_length=2),
        ),
    ]
