# Generated by Django 5.1.4 on 2025-01-07 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_utilities_utility_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
