# Generated by Django 5.1.4 on 2025-01-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_utilities_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='utility_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
