# Generated by Django 5.1.4 on 2025-01-05 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NA', 'Not Started'), ('IP', 'In Progress'), ('UR', 'Under Review'), ('CP', 'Completed'), ('DF', 'Deferred')], default='NA', max_length=2)),
            ],
        ),
    ]
